Repository ubccr/xdmod-appkernels, pull requests merged in 2019-10, with the labels that each got.

#69 update release notes and changelogs
  CHANGELOG.md
  xdmod-appkernels.spec.in
Labels: autodoc:ignore, release prep

#70 Convert documentation to use new style and TOC
  .editorconfig
  docs/_config.yml
  docs/_data/toc.yml
  docs/_includes/menu.md
  docs/ak-install-rpm.md
Labels: autodoc:ignore, documentation, release prep

#71 Update release date
  CHANGELOG.md
  xdmod-appkernels.spec.in
Labels: autodoc:ignore, release prep

#72 Version sync 8.5 -> 8.6
  .editorconfig
  CHANGELOG.md
  classes/AppKernel/PerformanceMap.php
  docs/_config.yml
  docs/_data/toc.yml
  docs/_includes/menu.md
  docs/ak-install-rpm.md
  xdmod-appkernels.spec.in
Labels: version sync

#73 Version sync 8.6 -> 9.0
  .editorconfig
  CHANGELOG.md
  classes/AppKernel/PerformanceMap.php
  docs/_data/toc.yml
  docs/_includes/menu.md
  docs/ak-install-rpm.md
  xdmod-appkernels.spec.in
Labels: version sync
